### ISSUE TITLE
How can I access amagama server localhost from another PC in the same LAN?

### ISSUE THREAD

**Issue by memoday** [translate/amagama#3203]
Hello everybody,

I managed to install amagama and it works just fine on the host machine. Now, I am trying to access it from another machine within the same local area network "LAN", but there nothing. I got the machine IP address and used as follows: 192.168.1.94:8888, but nothing shows up. Any idea? I have been trying for hours, but in vain. I appreciate your support.

Another question: 
How can you make amagama server running side by side next to an Apache server? Any guide on this?

thanks,
Mohamed

**Comment by unho** [comment]
> Hello everybody,
>
> I managed to install amaGama and it works just fine on the host machine. Now, I am trying to access it from another machine within the same local area network "LAN", but there nothing. I got the machine IP address and used as follows: 192.168.1.94:8888, but nothing shows up. Any idea? I have been trying for hours, but in vain. I appreciate your support.

I think that if you use the `--bind` argument you can attach it to some host name or IP address of your choice. Run `amagama --help` for more info. In case that doesn't provide enough info, see https://github.com/translate/amagama/blob/master/bin/amagama#L31-L35. 


> Another question: 
> How can you make amaGama server running side by side next to an Apache server? Any guide on this?

amaGama is a Flask app, so you can use any web server that supports WSGI to serve amaGama using this script bundled with amaGama https://github.com/translate/amagama/blob/master/wsgi.py.

Not sure which web server you want to use, but http://flask.pocoo.org/docs/0.10/deploying/mod_wsgi/ explains how to get it working with Apache. Search on the Internet for how to setup a Flask app using any other web server of your choice if you don't like Apache.

**Comment by unho** [comment]
Please let us know if this solves your problems.

**Comment by memoday** [comment]
Thank you so much for your prompt reply. Yes, I wanted to run it behind Apache server and thanks for the link. In Amagama folder, there is a file called "wsgi.py". Is this the one to use for this setup? Or should I create a new one named "amagama.wsgi.py"? I am a bit confused. Maybe, if there is a virtual machine for an Apache setup, it would make things easier. Thanks again for your support. Please correct me if I am wrong.

**Comment by unho** [comment]
Yes, that `wsgi.py` is the one you should use. I already linked it in one of my previous comments. You can rename it to the name you want.

No, there is not a virtual machine for an Apache setup.
