### ISSUE TITLE
search is case sensitive

### ISSUE THREAD

**Issue by memoday** [translate/amagama#3204]
Hi team,

I noticed that search in amagama is case-sensitive. So, search for 'select' for example won't get "Select". How to make search case-insensitive?

By the way, Amagama is really a great fast piece of software. I like it very much. 

Thanks,
Mohamed

**Comment by unho** [comment]
Will require changing amaGama code, if I am not wrong. I am not familiar with this. Anyway it will impact performance, and amaGama was built for performance.

**Comment by unho** [comment]
This is actually done in third party software, and not in amaGama, so closing this.
