### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by memoday** [translate/amagama#3206]
Hello team,

I am trying to get data out of amagama server to a Drupal site. I am using a module that retrieves data from JSON. Here is a link to the tutorial http://frontmag.no/artikler/utvikling/show-external-json-data-drupal-views, but for some reason it doesn't work because there is no key given when I go for example to http://0.0.0.0.0:8888/tmserver/en/ar/unit/review

Here is what I get when I go to that path:

```json
[{
    "quality": 83.33333333333334,
    "rank": 100.0,
    "source": "Review",
    "target": "ØªØ­ÙƒÙŠÙ…"
}, {
    "quality": 71.42857142857143,
    "rank": 100.0,
    "source": "Reviews",
    "target": "Ø§Ø³ØªØ¹Ø±Ø§Ø¶"
}]
```

The Drupal module requires a path to the JSON file. Where is this located in amagama installation? I hope you can really help me with this one since I am not familiar with JSON. 

Thanks again for your support and the prompt replies. I appreciate it.

Kind regards,
Mohamed

**Comment by unho** [comment]
I am not sure I follow. What you got is valid JSON. The view that created it is https://github.com/translate/amagama/blob/master/amagama/views/api.py#L68-L80

**Comment by memoday** [comment]
I need to path the URL of the JSON file to the module. What is the path or URL to the JSON file? 
The JSON file output should be as follows. As you can see, there is a key here in this format, but in Amagama output, there is no key.

{
  'persons':[
    {
      'firstName': 'Geir',
      'lastName': 'Gulland',
      'position': 'CEO & partner',
      'imageUrl': 'http://www.frontkom.no/img/profiles/Geir.jpg',
      'contact':{
        'facebook': 'https://www.facebook.com/geir.gulland',
        'linkedin': 'http://www.linkedin.com/profile/view?id=6151058'
      }
    },
...
]}

**Comment by unho** [comment]
amaGama returns valid JSON. I checked with four random JSON validators I found googling:

- http://jsonlint.com/
- https://jsonformatter.curiousconcept.com/
- http://codebeautify.org/jsonvalidate
- http://www.freeformatter.com/json-validator.html

So I don't understand what is your problem with that output. Perhaps are you having trouble to parse it?

**Comment by unho** [comment]
We got no further feedback, so closing this.
