### ISSUE TITLE
German returns 404

### ISSUE THREAD

**Issue by AyKuTmania** [translate/amagama#3211]
Hey guys,

I would like using your TMS, but it seems to be there is no possibility to translate from german?
Here's a test of _your_ live-system:
English to German works fine:
https://amagama-live.translatehouse.org/api/v1/en/de/unit/?source=technology
But from German, I'm getting an error:
https://amagama-live.translatehouse.org/api/v1/de/en/unit/?source=Technik

Thanks for you help!

Best Regards,
Sebastian

**Comment by unho** [comment]
While the underlying code allows any number of source languages, in that particular deployment we only have English as source language, as you can see in https://amagama-live.translatehouse.org/api/v1/languages/

If you want to support translating from German, or any other language, I suggest you to setup your own amaGama install.

Sadly we are not going to offer any other source language than English anytime soon. So closing this as wontfix.
