### ISSUE TITLE
TM sources for Kazakh language

### ISSUE THREAD

**Issue by crayxt** [translate/amagama#3213]
Dear developers,
I am working mostly on Mozilla's and LibreOffice's Pootle instances. So I would like to know the sources for Kazakh suggestions from TM (amagama). It seems like those are coming from Kazakh KDE translations as well. If it is true, I'd like to ask you to exclude KDE Kazakh translation from suggestions for Pootle. Those translations are too different in style from Mozilla and LibreOffice translations.
Thanks,

**Comment by dwaynebailey** [comment]
@crayxt the amagama ones will include KDE.  We don't have an easy way to exclude languages in uploads, so I'll keep this open till we do.

On both Mozilla and LibreOffice, they will have amagama results plus their local TM.  Their local ones will come first, so hopefully knowing that you can more easy distinguish.

**Comment by crayxt** [comment]
I suppose this is no longer actual.
