### ISSUE TITLE
Dropdowns in the live instance is empty

### ISSUE THREAD

**Issue by jandersson-svt** [translate/amagama#3216]
The live instance at https://amagama-live.translatehouse.org/ shows empty dropdowns.

**Comment by friedelwolff** [comment]
I can confirm, and will try to look into this. At first glance it is related to issue #3214, but I think something else is also wrong on the server.

**Comment by friedelwolff** [comment]
Ok, it was an unrelated issue on the server. It is fixed, although the certificate is still a problem, which I'll try to look at soon.

**Comment by hanklank** [comment]
Thank you very much, great to see it is working again.!
